name: build

on:
  push:
    branches:
      - master

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@V3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          PREV_COMMIT=${{ github.event.before }}
          CURR_COMMIT=${{ github.sha }}

          # Handle first commit or missing history
          if [ -z "$PREV_COMMIT" ] || [ "$PREV_COMMIT" = "0000000000000000000000000000000000000000" ]; then
            echo "First commit detected or missing history. Listing only new files."
            CHANGED_FILES=$(git ls-files '*.md')  # Get all .md files
          else
            echo "Comparing changes between $PREV_COMMIT and $CURR_COMMIT"
            CHANGED_FILES=$(git diff --name-only $PREV_COMMIT $CURR_COMMIT -- '*.md')
          fi

          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed markdown files detected."
            echo "FILES=" >> $GITHUB_ENV
          else
            echo "Changed files:"
            echo "$CHANGED_FILES"

            echo "FILES<<EOF" >> $GITHUB_ENV
            echo "$CHANGED_FILES" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Translate changed files with ChatGPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          for FILE in $FILES; do
            echo "Translating: $FILE"

            TRANSLATION=$(curl -s https://api.openai.com/v1/chat/completions \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{
                "model": "gpt-4",
                "messages": [
                  {"role": "system", "content": "You are a translator with a specialty in software development. You must accurately translate the text while preserving technical terms that do not have a precise Persian equivalent. Do not translate such technical words and keep them intact."},
                  {"role": "user", "content": "Translate this to Persian:\n'"$(cat $FILE)"'"}
                ]
              }' | jq -r '.choices[0].message.content')

            # Save the translation
            TRANSLATED_FILE="${FILE%.md}-fa.md"
            echo "$TRANSLATION" > "$TRANSLATED_FILE"
            echo "Saved translation to $TRANSLATED_FILE"
          done

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for translated file changes
        id: check_translation_changes
        run: |
          if git ls-files --others --exclude-standard *-fa.md | grep .; then
            echo "New translated files detected."
            echo "changes_detected=true" >> $GITHUB_ENV
          elif git diff --quiet *-fa.md; then
            echo "No changes detected."
          else
            echo "Modified translated files detected."
            echo "changes_detected=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.changes_detected == 'true'
        run: |
          git add *-fa.md
          git commit -m "Add translated files"

      - name: Push changes
        if: env.changes_detected == 'true'
        run: |
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/imaun/website.git HEAD:master
